name: Kind Cluster

on: [push]

jobs:
  create-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create kind cluster
      run: kind create cluster --name my-cluster

    - name: Get cluster info
      run: kubectl cluster-info --context kind-my-cluster

    - name: Apply Kubernetes manifests
      run: kubectl apply -f k8s-manifests/

    - name: Run tests
      run: |
        # Add your test commands here
        echo "Running tests..."
