name: matrix-env-gh-secret-npm

on:
  push:
    paths:
      - 'app1/**'
      - 'app2/**'
  pull_request:
    paths:
      - 'app1/**'
      - 'app2/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'uat'
        type: choice
        options:
          - dev
          - test
          - uat
          - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [app1, app2]
#        environment: [dev, uat]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Configure npm to use GitHub Package Registry for app1
      if: matrix.app == 'app1'
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GITHUB_TOKEN }}" > app1/.npmrc

    - name: Configure npm to use GitHub Package Registry for app2
      if: matrix.app == 'app2'
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GITHUB_TOKEN }}" > app2/.npmrc

    - name: Install dependencies
      run: |
        cd ${{ matrix.app }}
        npm install

    - name: Fix vulnerabilities
      run: |
        cd ${{ matrix.app }}
        npm audit fix

    - name: Print npm logs
      if: failure()
      run: cat /home/runner/.npm/_logs/*.log

    - name: Run tests
      run: |
        cd ${{ matrix.app }}
        npm test

    - name: Build Docker image
      run: |
        cd ${{ matrix.app }}
        docker build -t myregistry/${{ matrix.app }}:${{ github.sha }} .

    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login myregistry.azurecr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image to ACR
      run: |
        docker push myregistry/${{ matrix.app }}:${{ github.sha }}

    - name: Deploy to AKS
      run: |
        cd ${{ matrix.app }}
        kubectl apply -f deployment-${{ matrix.environment }}.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
