name: Deploy Applications

on:
  push:
    paths:
      - 'app2/**'
  pull_request:
    paths:
      - 'app2/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [app1, app2]
        environment: [dev, test, uat, prod]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd ${{ matrix.app }}
        npm install

    - name: Run tests
      run: |
        cd ${{ matrix.app }}
        npm test

    - name: Build Docker image
      run: |
        cd ${{ matrix.app }}
        docker build -t myregistry/${{ matrix.app }}:${{ github.sha }} .

    - name: Log in to Docker Hub build and push
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login myregistry.azurecr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push myregistry/${{ matrix.app }}:${{ github.sha }}


