name: CI

on: [push]
env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set build ID
      run: echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: echo "Deploying build ID ${{ env.BUILD_ID }}"
