name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set build ID
      id: build_id
      run: echo "::set-output name=BUILD_ID::$(date +%s)"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: echo "Deploying build ID ${{ needs.build.outputs.BUILD_ID }}"
